name: wash_it
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dots_indicator: ^2.1.1

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  horizontal_text_line: ^0.0.2
  http: ^1.2.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.2
  firebase_ui_auth: ^1.15.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.0.6
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  google_places_flutter: ^2.0.9
  url_launcher: ^6.3.0
  firebase_database: ^11.1.4
  intl: ^0.19.0
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  flutter_stripe: ^11.1.0
  flutter_inappwebview: ^6.1.3
  lazy_loading_list_view: ^0.0.7
  shimmer_loading: ^0.0.1
  animated_notch_bottom_bar: ^1.0.3
  shimmer_pro: ^0.0.6
  shimmer: ^3.0.0
  razorpay_flutter: ^1.3.7
  flutter_text_box: ^0.0.1
  uuid: ^4.5.1
  firebase_messaging: ^15.1.3
  app_settings: ^5.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  firebase_crashlytics: ^4.1.3
  fl_chart: ^0.69.0
  internet_connection_checker_plus: ^2.5.2
  persistent_bottom_nav_bar_plus: ^5.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
      - assets/image/






  #fonts:
   #  - family: Schuyler
     #  fonts:
       #  - asset: fonts/Schuyler-Regular.ttf
     #    - asset: fonts/Schuyler-Italic.ttf
        #   style: italic
    # - family: Trajan Pro
    #   fonts:
     #    - asset: fonts/TrajanPro.ttf
       #  - asset: fonts/TrajanPro_Bold.ttf
       #    weight: 700


